### ISSUE TITLE
Netbox integration

### ISSUE THREAD

**Issue by dal00** [metal3-io/ip-address-manager#18]
**User Story**

As a user I would like to be able to use Netbox to manage my IP addresses allocation to integrate with my current solutions.

**Detailed Description**

Some investigation is needed to figure out if it would be possible to use Netbox as a backend for the IP address generation. If possible, a design proposal should be submitted to propose the changes needed to do that. Then implementation could follow. This is a high level issue to track work in this area.

**Anything else you would like to add:**

I believe that Netbox is interesting to focus on since it is an open source project with an active community.

/kind feature

**Comment by maelk** [comment]
That sounds good! Are you planning to work on the proposal you are mentioning ? I think we need to have some design discussion on how to support multiple backends, independently of the backend. That means quite some refactoring, but would enable to add Infoblox as a backend too at the same time.

**Comment by dhellmann** [comment]
Could we use the cluster API model, and use the same API resource with completely independent controllers?

**Comment by dal00** [comment]
> That sounds good! Are you planning to work on the proposal you are mentioning ? I think we need to have some design discussion on how to support multiple backends, independently of the backend. That means quite some refactoring, but would enable to add Infoblox as a backend too at the same time.

I don't know yet. I have only looked briefly at the project and found it interesting. Then wanted to shine some light on that Netbox as it might be more accessible for developers and users to start with than Infoblox.
