### ISSUE TITLE
Add an infoblox backend

### ISSUE THREAD

**Issue by maelk** [metal3-io/ip-address-manager#4]
**User Story**

As a user I would like to be able to use infoblox to manage my IP addresses allocation to integrate with my current solutions. 

**Detailed Description**

Some investigation is needed to figure out if it would be possible to use infoblox as a backend for the IP address generation. If possible, a design proposal should be submitted to propose the changes needed to do that. Then implementation could follow. This is a high level issue to track work in this area.

/kind feature

**Comment by dhawal55** [comment]
+1

**Comment by MnrGreg** [comment]
@maelk @dhawal55 @abhinavnagaraj I've started a rough design doc here. Would appreciate any inputs.

https://docs.google.com/document/d/1gfJleq34l-ZTOKJ30UYSQqmlTj7FHqEyMF3q4_W4zMc/edit?usp=sharing
Please comment and then I can add you as editors.

**Comment by dhawal55** [comment]
@mariusgrigoriu Can you please review the design doc and comment if needed?

**Comment by mariusgrigoriu** [comment]
Thanks. It's a good start. I will get some other folks on the team to review too.

**Comment by maelk** [comment]
Could you please give write access to metal3-dev@googlegroups.com for edit rights ? (or at least suggestions)

This is a nice first step with clear user stories and goals. I think we should take the discussion further with the design part, in order to make a mechanism that would allow us to plug more than the infoblox backend.

**Comment by MnrGreg** [comment]
@maelk edit access has been added for metal3-dev@googlegroups.com. if any others need please ping here.
