### ISSUE TITLE
How can i use this project?

### ISSUE THREAD

**Issue by matthewei** [metal3-io/ip-address-manager#474]
**What steps did you take and what happened:**
Hi Team, I can't find any use-case for this project? could you share me a example how to use it?

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- CAPM3 version:
- IPAM version:
- Minikube version:
- environment (metal3-dev-env or other):
- Kubernetes version: (use `kubectl version`):

/kind bug

**Comment by Rozzii** [comment]
/triage accepted
So as a starting point @matthewei  I would recommend reading this https://book.metal3.io/ipam/introduction.
@peppi-lotta  I have heard that you are doing comparison between IPAM and CAPI-IPAM , could you please comment here whether you think Metal3-IPAM will remain relevant or should @matthewei  focus on CAPI IPAM more ?

**Comment by peppi-lotta** [comment]
ItCAPI-IPAM is very similar to ip-address-manager and has much of the same code. These might be some issue with cluster-api's move when performed with their IPAM in use. I'm but discussing with the developers to solve it. Metal3 could be moving to use CAPI's IPAM if these problems are solved. So I think it might be wiser to focus on CAPI's IPAM.

**Comment by matthewei** [comment]
@peppi-lotta you mean we are ready to abandon this project?

**Comment by Rozzii** [comment]
> @peppi-lotta you mean we are ready to abandon this project?

@peppi-lotta was referring to Metal3's own IPAM implementation. There is an ongoing evaluation of our own IPAM implementation that was created way before CAPI had an IPAM implementation, but if the CAPI implementation would fulfill all of the Metal3's needs then there is no reason to maintain our own.

**Comment by matthewei** [comment]
> > @peppi-lotta you mean we are ready to abandon this project?
> 
> @peppi-lotta was referring to Metal3's own IPAM implementation. There is an ongoing evaluation of our own IPAM implementation that was created way before CAPI had an IPAM implementation, but if the CAPI implementation would fulfill all of the Metal3's needs then there is no reason to maintain our own.

yes, i see
