### ISSUE TITLE
Golangci-lint does not lint release note tools

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/ip-address-manager#767]
Golangci-lint does not lint release note tools, only root + api dirs.

Add other directories with .go files to linter config and then fix the go files if linter fails on them.

/kind bug

**Comment by wallchristopher** [comment]
I think I understand the issue and am willing to help

**Comment by tuminoid** [comment]
I updated description to be more specific, just in case.

/assign @wallchristopher
